image: maven:3.9.4-eclipse-temurin-21

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository
test:
  stage: test
  script:
    - docker --version
    - ./mvnw test -Dspring.profiles.active=test
    -
build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar


