stages:
  - test
  - build

default:
  image: maven:3.9.4-eclipse-temurin-21

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  only:
    - merge_requests
    - dev
  script:
    - echo "Running tests for Spring Boot application..."
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week

build:
  stage: build
  only:
    - dev
  script:
    - echo "Building Spring Boot application..."
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
