image: maven:3.9.4-eclipse-temurin-21

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"

cache:
  paths:
    - .m2/repository

# Stage for running tests
test:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw clean verify
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - target/failsafe-reports/*.xml
  only:
    - dev
    - main

# Stage for building the application
build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main
