image: maven:3.9.4-eclipse-temurin-21

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_HOST: "unix:///var/run/docker.sock"

cache:
  paths:
    - .m2/repository

# Стадия сборки
build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main

# Стадия тестирования
test:
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - chmod +x mvnw
    - ./mvnw test
    - ./mvnw verify
  only:
    - dev
    - main
