image: maven:3.8.6-openjdk-17

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw clean test
  only:
    - merge_requests
    - dev

build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - module1/target/*.jar
      - module2/target/*.jar
      - module3/target/*.jar
  only:
    - dev
    - main
