stages:
  - test
  - build

services:
  - postgres:13

variables:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST: postgres

default:
  image: maven:3.9.4-eclipse-temurin-21
  cache:
    paths:
      - .m2/repository/

test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  services:
    - postgres:13
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week

build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
