image: maven:3.9.4-eclipse-temurin-21

services:
  - docker:24.0-dind

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: "localhost"
  TESTCONTAINERS_RYUK_DISABLED: "true"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main

test:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw clean test
  only:
    - dev
    - main



