stages:
  - test
  - build

default:
  image: maven:3.9.4-eclipse-temurin-21

services:
  - name: postgres:14
    alias: postgres
  - name: redis:7
    alias: redis

variables:
  POSTGRES_DB: todo_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/todo_db"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
  REDIS_HOST: "redis"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw clean test -Dspring.profiles.active=test
  only:
    - merge_requests
    - dev

build:
  stage: build
  script:
    - echo "Building application..."
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
