stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_RYUK_DISABLED: "true"

services:
  - docker:dind

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean test
  only:
    - merge_requests
    - dev

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  only:
    - merge_requests
    - dev