image: maven:3.9.4-eclipse-temurin-21

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_HOST: "unix:///var/run/docker.sock"
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository


build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main

test:
  stage: test
  services:
    - docker:dind
  script:
    - docker ps
    - chmod +x mvnw
    - ./mvnw test
    - ./mvnw verify
  only:
    - dev
    - main
