image: docker:24.0.2

services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

before_script:
  - apk add --no-cache openjdk-21-jdk maven
  -
test:
  stage: test
  script:
    - echo "Checking Docker availability..."
    - docker --version
    - echo "Running tests with Maven..."
    - ./mvnw test -Dspring.profiles.active=test
  only:
    - dev
    - main
    -
build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main


