image: maven:3.9.4-eclipse-temurin-21

services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main

test:
  stage: test
  script:
    - echo "Checking Docker availability..."
    - docker --version
    - echo "Running tests with Maven..."
    - ./mvnw test -Dspring.profiles.active=test
  only:
    - dev
    - main
