image: maven:3.9.4-eclipse-temurin-21

stages:
  - test
  - build

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  TESTCONTAINERS_HOST_OVERRIDE: "localhost"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_RYUK_DISABLED: "true"

services:
  - docker:dind

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw clean test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
  only:
    - dev
    - main



build:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main
