image: docker:24.0.6

stages:
  - test
  - build

services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  TESTCONTAINERS_RYUK_DISABLED: "true"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository

test:
  stage: test
  before_script:

    - apk add --no-cache openjdk17 maven
    - java -version
    - mvn -version
    - docker info
  script:
    - chmod +x mvnw
    - ./mvnw clean verify
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - target/failsafe-reports/*.xml
  only:
    - dev
    - main


build:
  stage: build
  before_script:
    - apk add --no-cache openjdk17 maven
    - java -version
    - mvn -version
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - dev
    - main
