stages:
  - test
  - build

default:
  image: maven:3.9.4-eclipse-temurin-21
  services:
    - docker:20.10.23-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  DOCKER_TLS_VERIFY: "0"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -B"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - echo "Running tests for Spring Boot application..."
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week
  only:
    - merge_requests
    - dev

build:
  stage: build
  script:
    - echo "Building Spring Boot application..."
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - dev
