image: docker:latest

services:
  - docker:20.10.24-dind

variables:
  MAVEN_OPTS: "-Dfile.encoding=UTF-8"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_RYUK_DISABLED: "true"
  SPRING_PROFILES_ACTIVE: test

stages:
  - test
  - build

cache:
  paths:
    - .m2/repository

before_script:
  # Подтверждение запуска Docker демона
  - docker info

test:
  stage: test
  image: maven:3.8.8-openjdk-21
  script:
    - ./mvnw clean test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - target/*.log
    expire_in: 1 week

build:
  stage: build
  image: maven:3.8.8-openjdk-21
  script:
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
