version: "1.0"

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app