services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    networks:
      - spring
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

networks:
  spring:
    driver: bridge