
CREATE TABLE tasks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted       BOOLEAN,
    task_description VARCHAR(255)                            NOT NULL,
    task_header      VARCHAR(255)                            NOT NULL,
    task_priority    VARCHAR(255)                            NOT NULL,
    task_status      VARCHAR(255)                            NOT NULL,
    assignee_id      BIGINT,
    author_id        BIGINT,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    roles   VARCHAR(255) NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, roles)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(32)                             NOT NULL,
    is_banned  BOOLEAN,
    is_deleted BOOLEAN,
    password   VARCHAR(1024)                           NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

CREATE TABLE commentaries
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    commentary_header VARCHAR(320),
    commentary_text   TEXT                                    NOT NULL,
    creation_date     TIMESTAMP WITHOUT TIME ZONE,
    is_deleted        BOOLEAN,
    task_id           BIGINT,
    user_id           BIGINT,
    CONSTRAINT commentaries_pkey PRIMARY KEY (id)
);

ALTER TABLE commentaries
    ADD CONSTRAINT fk4w16kqj6nkij4kgohharsbmhq FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tasks
    ADD CONSTRAINT fkekr1dgiqktpyoip3qmp6lxsit FOREIGN KEY (assignee_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tasks
    ADD CONSTRAINT fkhods8r8oyyx7tuj3c91ki2sk1 FOREIGN KEY (author_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE commentaries
    ADD CONSTRAINT fkktau8xlq8xnu8p423pi8ympyf FOREIGN KEY (task_id) REFERENCES tasks (id) ON UPDATE NO ACTION ON DELETE NO ACTION;